apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: imagepull-docker
      containers:
      - name: nginx
        image: nginx:mainline-alpine3.18-slim
        imagePullPolicy: Always
        ports:
          - containerPort: 8082
---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: nginx
  type: LoadBalancer
